services:

  termix:
    image: ghcr.io/lukegus/termix:latest
    container_name: termix
    restart: unless-stopped
    ports:
      - "8200:8080"
    volumes:
      - ./termix-data:/app/data
    environment:
      PORT: "8080"

